backend:
  name: github
  repo: KentaKodashima/kentakodashima-com
media_folder: static/assets
public_folder: /assets
collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects'
    slug: '{{slug}}'
    create: true
    fields:
      - { name: 'templateKey', label: 'Template Key', widget: 'hidden', default: 'project-detail' }
      - { name: title, label: Title }
      - { name: priority, label: Priority, widget: number, default: 0, valueType: int }
      - { name: categoryType, label: Media Type, widget: select, options: ['Web', 'Mobile'] }
      - { name: thumbnail, label: Thumbnail Image, widget: image }
      - { name: thumbnailSubtitle, label: Thumbnail Subtitle, widget: string }
      - { name: mainImages, label: Main Images, widget: list, field: { name: image, label: Image, widget: image } }
      -   name: appLinks
          label: App or Website Links
          widget: list
          required: false
          fields:
            - name: appLink
              label: App or Website Link
              widget: object
              fields:
                - { name: url, label: URL, wdget: string }
                - { name: linkType, label: Media Type, widget: select, options: ['iOS', 'Android', 'Web', 'GitHub'] }
      - { name: about, label: About this project, widget: markdown }
      - { name: technologies, label: Technologies, widget: list, field: { name: technology, label: Technology Name, widget: string } }
      - { name: extraImages, label: Extra Images, widget: list, required: false, field: { name: image, label: Image, widget: image } }

  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: priority, label: Priority, widget: number, default: 0, valueType: int }
      - { name: thumbnail, label: Thumbnail Image, widget: image }
      - { name: url, label: URL }
      - { name: date, label: Date, widget: datetime }
      - { name: intro, label: Intro, widget: markdown }